# Generated by Django 4.1.7 on 2023-03-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('Новость', 'Новость'), ('Статья', 'Статья')], default='Новость', max_length=10),
        ),
    ]
